FROM golang:1.26 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/order-api .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /out/order-api /app/order-api

CMD ["/app/order-api"]